config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :articles
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true,
                      length: { minimum: 5 }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
      end
      
    def show
        @article = Article.find(params[:id])
      end
    
    def new
      @article = Article.new      
    end

    def edit
      @article = Article.find(params[:id])
    end

    def create
        #@article = Article.new(params[:article])
        #@article = Article.new(params.require(:article).permit(:title, :text))
        @article = Article.new(article_params)
        
        #@article.save
        #redirect_to @article
        if @article.save
          redirect_to @article
        else
          render 'new'
        end
      end

      def update
        @article = Article.find(params[:id])
       
        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
      end

      def destroy
        @article = Article.find(params[:id])
        @article.destroy
       
        redirect_to articles_path
      end
      
      private
      def article_params
        params.require(:article).permit(:title, :text)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
    
     <% if @article.errors.any? %>
       <div id="error_explanation">
         <h2>
           <%= pluralize(@article.errors.count, "error") %> prohibited
           this article from being saved:
         </h2>
         <ul>
           <% @article.errors.full_messages.each do |msg| %>
             <li><%= msg %></li>
           <% end %>
         </ul>
       </div>
     <% end %>
    
     <p>
       <%= form.label :title %><br>
       <%= form.text_field :title %>
     </p>
    
     <p>
       <%= form.label :text %><br>
       <%= form.text_area :text %>
     </p>
    
     <p>
       <%= form.submit %>
     </p>
    
   <% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>


<% if false %>
<%= form_with(model: @article) do |form| %>
 <% if @article.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@article.errors.count, "error") %> prohibited
       this article from being saved:
     </h2>
     <ul>
       <% @article.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
 <p>
   <%= form.label :title %><br>
   <%= form.text_field :title %>
 </p>
 <p>
   <%= form.label :text %><br>
   <%= form.text_area :text %>
 </p>

 <p>
   <%= form.submit %>
 </p>
<% end %>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>

<table>
 <tr>
   <th>Title</th>
   <th>Text</th>
 </tr>

 <% @articles.each do |article| %>
   <tr>
     <td><%= article.title %></td>
     <td><%= article.text %></td>
     <td><%= link_to 'Show', article_path(article) %></td>
     <td><%= link_to 'Edit', edit_article_path(article) %></td>
     <td><%= link_to 'Destroy', article_path(article),
     method: :delete,
     data: { confirm: 'Are you sure?' } %></td>     
     </tr>
 <% end %>
</table>

<%= link_to 'Back', root_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<% if false %>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>    
    
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text:</strong>
<%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/blabla.html.erb
<!--<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>-->

<h1>Fuck off!</h1>

app/views/welcome/index.html.erb
<!--<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>-->

<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>